import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";

export const metadata: Metadata = {
  title: "Skillnex — Employee ROI & Impact Dashboard",
  description:
    "Department-aware employee ROI analysis with LLM-generated review narratives.",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-full flex flex-col">
          <header className="border-b bg-background">
            <div className="mx-auto max-w-6xl px-6 py-4 flex items-center justify-between">
              <Link href="/" className="flex items-center gap-2">
                <span className="inline-block h-6 w-6 rounded bg-accent" />
                <span className="font-semibold tracking-tight">Skillnex</span>
                <span className="text-xs text-muted-foreground ml-2">MVP demo</span>
              </Link>
              <nav className="flex items-center gap-6 text-sm">
                <Link href="/dashboard" className="hover:underline">
                  Dashboard
                </Link>
                <Link href="/integrations" className="hover:underline">
                  Integrations
                </Link>
              </nav>
            </div>
          </header>
          <main className="flex-1 mx-auto w-full max-w-6xl px-6 py-10">{children}</main>
          <footer className="border-t text-xs text-muted-foreground">
            <div className="mx-auto max-w-6xl px-6 py-4">
              Skillnex — demo build. Metrics are computed from uploaded data. Narratives
              generated by Claude; review before using in performance decisions.
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
