import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";

export const metadata: Metadata = {
  title: "Skillnex — Employee ROI & Impact",
  description:
    "Department-aware employee ROI analysis with review-ready narrative summaries.",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,400;9..144,500;9..144,600&display=swap"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Geist:wght@400;500;600&family=Geist+Mono:wght@400;500&display=swap"
        />
      </head>
      <body>
        <div className="min-h-full flex flex-col bg-paper">
          <header className="border-b border-border bg-paper">
            <div className="mx-auto max-w-content px-xl py-lg flex items-center justify-between">
              <Link href="/" className="flex items-baseline gap-md">
                <span className="font-display text-2xl font-medium tracking-tight text-ink">
                  Skillnex
                </span>
                <span className="micro">MVP demo</span>
              </Link>
              <nav className="flex items-center gap-xl text-sm">
                <Link
                  href="/dashboard"
                  className="text-ink hover:text-accent transition-colors duration-short"
                >
                  Dashboard
                </Link>
                <Link
                  href="/integrations"
                  className="text-ink hover:text-accent transition-colors duration-short"
                >
                  Integrations
                </Link>
              </nav>
            </div>
          </header>
          <main className="flex-1 mx-auto w-full max-w-content px-xl py-4xl">
            {children}
          </main>
          <footer className="border-t border-border">
            <div className="mx-auto max-w-content px-xl py-lg text-xs text-muted-1">
              Skillnex — demo build. Metrics computed deterministically from uploaded
              data. Narratives generated by Claude; review before using in performance
              decisions.
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
